### ISSUE TITLE
build a firmware (7LED) with time-stretching globally disabled.

### ISSUE THREAD

**Issue by chrisbc** [mupaduw/DelugeFirmware#2]
Make the change - but how does it compare, what are the impacts?

- [x] Does it work? 
- [x] Does it sound good?
- [ ] what are impacts? Try recording, overdubbing, importing audiofiles . capture notes somewhere as issues(?) or in wiki?

**Comment by sichtbeton** [comment]
can one find the fw with this function somewhere?
