### ISSUE TITLE
audio clip start point

### ISSUE THREAD

**Issue by sichtbeton** [mupaduw/DelugeFirmware#5]
while you are mangling audio clips, maybe this would be doable too: when the audio clip is not timestretched anymore, let the user adjust the start of the clip similar to the end. 

this has been one of the most requested features to have for al long time.

**Comment by chrisbc** [comment]
@sichbeton FYI the codebase is a bit challenging for all this stuff & I'll really need a debugger to make things easier to GROK. You do know about the reverse-trim workaround I assume? And FWIW I think the start-point fix trim should be the same regardless of time-stretching.

**Comment by sichtbeton** [comment]
Yes, the reverse trim is the known workaround.

Ok, i wasn't aware of how complicated things are in this area.

So kudos to making this work!
